### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by nicholasbishop** [vector-of-bool/cmrc#1]
I didn't see any license in the code or readme.

**Comment by vector-of-bool** [comment]
Oh! Sorry, I never bothered to place one. Give me a few minutes and I'll add MIT. I honestly wasn't sure if anyone would ever find this project useful. Heh.

**Comment by nicholasbishop** [comment]
Thanks :) Can confirm that I found it useful.

**Comment by vector-of-bool** [comment]
Should have a license now. Thanks!
