### ISSUE TITLE
MSVC doesn't compile directory, since it contains a deque of itself

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/cmrc#8]
Currently, `directory` contains a `std::deque<directory> _dirs`. This `std::deque` is instantiated with the incomplete type `directory`.

```c++
class directory {
    std::deque<directory> _dirs;
```
As far as I can tell, this isn't allowed by the standard, and [MSVC rejects it](https://godbolt.org/z/eclwaq).

The cppreference entry on [`std::deque`](https://en.cppreference.com/w/cpp/container/deque#Template_parameters) seems to imply that it doesn't allow incomplete types, especially when juxtaposed with [`std::vector`](https://timsong-cpp.github.io/cppwp/n4659/vector#overview-3). It's not just cppreference, n4659 does the same:

[**\[vector\]**](https://timsong-cpp.github.io/cppwp/n4659/vector#overview-3):

> An incomplete type T may be used when instantiating vector if the allocator satisfies the allocator completeness requirements. T shall be complete before any member of the resulting specialization of vector is referenced.

[**\[deque\]**](https://timsong-cpp.github.io/cppwp/n4659/deque) has no such mention.

**Comment by vector-of-bool** [comment]
Fixed now.
